services:
    nginx:
        build: ./nginx
        hostname: nginx
        ports:
        - 80:80
        - 443:443
        networks:
        - backend

    ghost:
        image: ghost:5.94.2
        restart: always
        hostname: ghost
        ports:
        - 2368:2368
        environment:
            database__client: mysql
            database__connection__host: mysql
            database__connection__user: root
            database__connection__password: pw1234
            database__connection__database: ghost
        volumes:
        - ghost_data:/var/lib/ghost/content   
        networks:
        - backend
        depends_on:
        - mysql

    mysql:
        image: mysql:8.4.2
        restart: always
        hostname: mysql
        environment:
            MYSQL_ROOT_PASSWORD: pw1234
            MYSQL_DATABASE: ghost
        volumes:
        - mysql_data:/var/lib/mysql
        networks:
        - backend

    phpmyadmin:
        image: phpmyadmin:5.2.1
        restart: always
        hostname: phpmyadmin
        ports:
        - 8082:80
        environment:
            PMA_HOST: mysql
            MYSQL_ROOT_PASSWORD: pw1234
        networks:
        - backend

volumes:
    ghost_data:
    mysql_data:

networks:
    backend:
        driver: bridge